### ISSUE TITLE
FAILED TO EXECUTE: launcher_ldr radiant_mod.dll CoDBORadiant 

### ISSUE THREAD

**Issue by donohunt0** [Mythical-Github/Black-Ops-Mod-Tools-Installer#1]
Every time I try to boot up Radiant through the Mod Tools, it shows "FAILED TO EXECUTE: launcher_ldr radiant_mod.dll CoDBORadiant" in the console. And when I do try to go into Radiant, this time not going through the modtools and by going into the files, it asks for .prj files that the Modtools cannot create. How can I fix this?

**Comment by Mythical-Github** [comment]
You need to run the launcher as admin, the prj should already exist, if it doesn't you didn't properly follow the text prompts before using the tool
